"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-09 03:20:51.053515
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# ── 수동 보정 ────────────────────────────────────────────────────────────
# autogenerate 는 컬럼에 sa.Enum(...) 을 그대로 박아 놓는데, 그 경우
#   - upgrade   : create_table 이 CREATE TYPE 을 checkfirst 없이 실행 →
#                 중간에 실패한 마이그레이션을 다시 돌리면 DuplicateObjectError
#   - downgrade : DROP TYPE 을 아예 만들어주지 않음 →
#                 downgrade base 후 재-upgrade 가 "type already exists" 로 깨진다
# 두 증상 다 실제로 재현했다. 그래서 타입 수명을 여기서 명시적으로 관리한다.
# postgresql.ENUM(create_type=False) 는 "컬럼은 이 타입을 쓰되 생성은 하지 말라"는 뜻.
SEAT_STATUS = postgresql.ENUM(
    "AVAILABLE", "HELD", "BOOKED", name="seat_status", create_type=False
)
ORDER_STATUS = postgresql.ENUM(
    "PENDING", "PAID", "CANCELED", "FAILED", name="order_status", create_type=False
)
PAY_STATUS = postgresql.ENUM(
    "REQUESTED", "APPROVED", "FAILED", "REFUNDED", name="pay_status", create_type=False
)
ENUMS = (SEAT_STATUS, ORDER_STATUS, PAY_STATUS)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    for enum in ENUMS:
        enum.create(bind, checkfirst=True)

    op.create_table('outbox',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox'))
    )
    op.create_index('ix_outbox_unpublished', 'outbox', ['created_at'], unique=False, postgresql_where=sa.text('published_at IS NULL'))
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('venues',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venues'))
    )
    op.create_table('performances',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('venue_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('running_time_min', sa.Integer(), nullable=False),
    sa.Column('age_limit', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_performances_venue_id_venues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_performances'))
    )
    op.create_table('seats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('venue_id', sa.BigInteger(), nullable=False),
    sa.Column('zone', sa.Text(), nullable=False),
    sa.Column('row_label', sa.Text(), nullable=False),
    sa.Column('col_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_seats_venue_id_venues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seats')),
    sa.UniqueConstraint('venue_id', 'zone', 'row_label', 'col_no', name='uq_seat_position')
    )
    op.create_table('schedules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('performance_id', sa.BigInteger(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sale_opens_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['performance_id'], ['performances.id'], name=op.f('fk_schedules_performance_id_performances')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedules')),
    sa.UniqueConstraint('performance_id', 'starts_at', name='uq_schedule')
    )
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('status', ORDER_STATUS, server_default='PENDING', nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('booking_fee', sa.Integer(), server_default='0', nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('response_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('fk_orders_schedule_id_schedules')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_orders_idempotency_key'))
    )
    op.create_index('ix_orders_pending', 'orders', ['created_at'], unique=False, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_table('schedule_seats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('seat_id', sa.BigInteger(), nullable=False),
    sa.Column('grade', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('status', SEAT_STATUS, server_default='AVAILABLE', nullable=False),
    sa.Column('held_by', sa.BigInteger(), nullable=True),
    sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'HELD' AND held_by IS NOT NULL AND hold_expires_at IS NOT NULL) OR (status <> 'HELD' AND held_by IS NULL AND hold_expires_at IS NULL)", name=op.f('ck_schedule_seats_hold_shape')),
    sa.ForeignKeyConstraint(['held_by'], ['users.id'], name=op.f('fk_schedule_seats_held_by_users')),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('fk_schedule_seats_schedule_id_schedules')),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], name=op.f('fk_schedule_seats_seat_id_seats')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_seats')),
    sa.UniqueConstraint('schedule_id', 'seat_id', name='uq_schedule_seat')
    )
    op.create_index('ix_hold_expiry', 'schedule_seats', ['hold_expires_at'], unique=False, postgresql_where=sa.text("status = 'HELD'"))
    op.create_index('ix_seatmap', 'schedule_seats', ['schedule_id'], unique=False, postgresql_include=['seat_id', 'grade', 'price', 'status'])
    op.create_table('order_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('schedule_seat_id', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders')),
    sa.ForeignKeyConstraint(['schedule_seat_id'], ['schedule_seats.id'], name=op.f('fk_order_items_schedule_seat_id_schedule_seats')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items')),
    sa.UniqueConstraint('schedule_seat_id', name=op.f('uq_order_items_schedule_seat_id'))
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('pg_tid', sa.Text(), nullable=True),
    sa.Column('status', PAY_STATUS, nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('fee_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payments_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('pg_tid', name=op.f('uq_payments_pg_tid'))
    )
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_seatmap', table_name='schedule_seats', postgresql_include=['seat_id', 'grade', 'price', 'status'])
    op.drop_index('ix_hold_expiry', table_name='schedule_seats', postgresql_where=sa.text("status = 'HELD'"))
    op.drop_table('schedule_seats')
    op.drop_index('ix_orders_pending', table_name='orders', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_table('orders')
    op.drop_table('schedules')
    op.drop_table('seats')
    op.drop_table('performances')
    op.drop_table('venues')
    op.drop_table('users')
    op.drop_index('ix_outbox_unpublished', table_name='outbox', postgresql_where=sa.text('published_at IS NULL'))
    op.drop_table('outbox')
    # ### end Alembic commands ###

    # 테이블이 사라진 뒤에야 타입을 지울 수 있다. 순서를 바꾸면 의존성 오류.
    bind = op.get_bind()
    for enum in reversed(ENUMS):
        enum.drop(bind, checkfirst=True)
